service: xendit-assessment

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-south-1

functions:
  app:
    handler: app.server # reference the file and exported method
    events: # events trigger lambda functions
      - http: 
          path: /
          method: ANY
          cors: true
     